model:
  path: models/
  weights: coco     # new, last, coco, imagenet or custom path
  epochs: 10      # number of epochs to train for
  settings:
    name: coco_finetune_rgb
    mean_pixel: [128, 128, 128]
    image_shape: [512,512,3]
    backbone: resnet35
    num_classes: 2
    gpu_count: 1
    images_per_gpu: 2
    learning_rate: 0.001

dataset:
  path: /wisdom/wisdom-real/high-res
  train_indices: train_indices.npy
  val_indices: test_indices.npy
  images: color_ims
  masks: modal_segmasks

# name of the config file to save (within the dataset folder)
# note that this will be overwritten between multiple runs so
# you should name this uniquely for each run.
save_conf_name: coco_finetune_rgb_00.yaml
